// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddItem struct {
	RankingID string `json:"ranking_id"`
	Name      string `json:"name"`
}

type Item struct {
	ID        string `json:"id"`
	RankingID string `json:"ranking_id"`
	Name      string `json:"name"`
	Point     int    `json:"point"`
}

type NewRanking struct {
	Name string `json:"name"`
}

type Ranking struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Items []*Item `json:"items"`
}
